{
 "title": "Grafana - AOOP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Preço em Euros",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  min(price)::float as minimo,\r\n  max(price)::float as maximo,\r\n  avg(price)::float as media,\r\n  (\r\n    select PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY price) AS median\r\n    from dataset\r\n  )::float as mediana,\r\n  sum(price)::float as total\r\nfrom dataset\r\n"
    }
   ]
  },
  {
   "title": "Número total de Amostras",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Histograma Kitchen Area",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT kitchen_area FROM dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Histograma de Preços",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT price FROM dataset LIMIT 100 "
    }
   ]
  },
  {
   "title": "Desvio Padrão do Preço",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tSTDDEV(price) AS desvio_padrao,\r\n  avg(price) as media\r\nFROM dataset;"
    }
   ]
  },
  {
   "title": "1º/3º Quartil",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    percentile_cont(0.25) WITHIN GROUP (ORDER BY price) AS q1,\r\n    percentile_cont(0.5) WITHIN GROUP (ORDER BY price) AS q2,\r\n    percentile_cont(0.75) WITHIN GROUP (ORDER BY price) AS q3\r\nFROM dataset;"
    }
   ]
  },
  {
   "title": "Histograma de Área",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT area FROM dataset LIMIT 1000000 "
    }
   ]
  },
  {
   "title": "House Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  geo_lat,\r\n  geo_lon\r\nfrom dataset\r\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "HeatMap: Area, id_region, building_type em relação ao preço",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT price, id_region, building_type, area FROM dataset LIMIT 10000 "
    }
   ]
  }
 ]
}